name: Deploy

jobs:
  build:
    runs-on: ubuntu-latest

    - name: Deploy with gh-pages
      run: |
        echo "Deploy ghpages"
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}